enhancedTable/index.ts
enhancedTable/panel-manager.ts
enhancedTable/templates.ts

Addresses:
- point 4 here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3079
- point 3 here: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3077
- sorting indicator done according to [Material Guidelines](https://material.io/design/components/data-tables.html#anatomy) (scroll down to sorting tool)
- and @AleksueiR's request for better padding/CSS layout for `enhancedTable` (now uses Flexbox instead of floats)
Testing info on sister PR over here: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3104

Enhanced Table filter status, sorting indicator and css/layout

---

changelog.md
enhancedTable/index.ts
enhancedTable/tests/test.spec.js

Closes: 
- https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2931
- https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2932
- https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2933
- https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2934
Sister PR to (on the viewer repo): 
- https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3128
- We needed `legendapi` merged into `v3` asap for `enhancedTable` testing purposes (it is much easier to manipulate layers using `LegendItems` and `LegendGroups` instead of CSS selectors). 
- This PR makes `legendApi` compatible with the `enhancedTable` extension
- Also we fixed up [this test](https://github.com/fgpv-vpgf/plugins/compare/develop...ShrutiVellanki:legendapi?expand=1#diff-f1923b71550f5a6dc3eb14e3341d81a6L8) which always used to return true regardless of whether the table …

fix(enhancedTable): table works with legendAPI

---

enhancedTable/index.ts
enhancedTable/panel-manager.ts
enhancedTable/templates.ts

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3080
Make enhanced table grid keyboard accessible
Adds ability to tab in and out of table. Still requires fixing focusing panel after pressing layer in legend.  

feat(enhancedTable): make grid keyboard accessible

---

enhancedTable/custom-floating-filters.ts
enhancedTable/index.ts
enhancedTable/samples/ramp-config.json
enhancedTable/templates.ts
enhancedTable/tests/et.page.js
enhancedTable/tests/filter-test.spec.js

Helps close a part of: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3185
Selector column  was missing from `enhancedTable` even if it was specified in config
Checks the config for selector filters and adds it creating a drop down menu with multiple select-able items.
-   ~[ ] `changelog.md` has been updated~

feat(enhancedTable): add selector filter

---

enhancedTable/custom-floating-filters.ts
enhancedTable/index.ts
enhancedTable/panel-manager.ts
enhancedTable/samples/ramp-config.json
enhancedTable/templates.ts

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3185
- When default filters were on config, `enhancedTable` didn't have them automatically applied
- placeholder values were not available for all filter types
- not all placeholders had proper translations
- no consistent theme for disabled filters.
- default values for all filter types (string, selector, date and number)
- placeholders added for text filters and date filters
- placeholders have french translations
- static filters made to look uniform accross different filter types (white overlay)
Look at the following layers for each filter type (some with default values and static filters)
| Layer          | Column Filter Types          
| ------------- |:-------------:| 
| No initial filter 2        | number, selector (default …

feat(enhancedTable): table filters obey config

---

bin/test/ramp/rv-styles.css
enhancedTable/config-manager.ts
enhancedTable/custom-floating-filters.ts
enhancedTable/details-and-zoom-buttons.ts
enhancedTable/index.ts
enhancedTable/panel-manager.ts
enhancedTable/panel-rows-manager.ts
enhancedTable/panel-state-manager.ts
enhancedTable/samples/ramp-config.json
enhancedTable/templates.ts

**NOTE: The reload button itself doesn't toggle / refresh the table. This will come in a future PR addressing bug  fixes**
Closes: 
- https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3214
- https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3234
- https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3236
- When `enhancedTables`were reloaded/reopened, they did not preserve table states.
- Table details and zoom fail for filtered tables (returns wrong point)
- Selector filter would appear to fail because default global filter search text was not showing
Required table states:
- visibility (layer and symbology)
- filter status
- column filters
- whether table is maximized/split view
- …

Table state on reload/reopen, fix details and zoom bug, default global filter text shows

---

enhancedTable/index.ts
enhancedTable/panel-manager.ts

Make sure panel close deregisters table listeners
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3235
Figure out what to do to an open table when its layer is reloaded. 
Also in this PR but without an issue is that the panel close button wouldn't destroy the table completely.
Close an open table if its layer is reloaded. 
Enhance the panel's close button so it handles the table destruction properly. 
https://dane-thomas.github.io/plugins/327d369c718ba0bd01efc1666467b415e97fe985/enhancedTable/samples/et-index.html
-   [x] PR has only one commit (squash …

feat(enhancedTable): close table on layer reload

---

enhancedTable/panel-manager.ts
enhancedTable/panel-rows-manager.ts
enhancedTable/panel-state-manager.ts
enhancedTable/templates.ts

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3267
Extent filter not applied to/removed from the table on enable/disable. 
Extent filter not applied on table open when previously enabled.
Filter by extent stays enabled between tables.
Triggers extent filter on enable and removes it on disable.
Applies extent filter on open if enabled.
Store extent filter enabled flag on state so it's preserved between table opens.
https://dane-thomas.github.io/plugins/df6721a912f43dbf7afba64ccba2d2956c67b0ad/enhancedTable/samples/et-index.html
-   ~~[ ] Test specs are up-to-date & cover all changes/additions made by this PR.~~
-   ~~[ ] `npm run test` passes locally.~~
-   [x] PR has only …

fix(enhancedTable): fix extent filter not applied

---

enhancedTable/custom-floating-filters.ts
enhancedTable/grid-accessibility.ts
enhancedTable/index.ts
enhancedTable/panel-manager.ts

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3290
Vertical scroll would cause the focus to jump from filter to grid
Adds check if focus is changing via mouse
https://dane-thomas.github.io/plugins/c984af3592b0dd35aff755aff2782c8bc040cfd3/enhancedTable/samples/et-index.html

fix(enhancedTable): focus shift on vertical scroll

---

enhancedTable/panel-manager.ts
lib/enhancedTable/panel-manager.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3306
Left most column did not have a visible sort indicator so it wasn't obvious that you could sort columns. Now it does. 
Test: http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/update-wfs-import/dev/samples/index-samples.html
-   ~[ ] Test specs are up-to-date & cover all changes/additions made by this PR.~
-   ~[ ] `npm run test` passes locally.~
-   ~[ ] Documentation is up-to-date - any changes or additions have been noted~
-   ~[ ] `changelog.md` has been updated~

fix(enhancedTable): sort arrow indicator on first column

---

enhancedTable/templates.ts

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3342
Pressing the up arrow key to navigate the menu closes it
Removes focus manager code that was on the menu. It was ca using the strange behavior 
[Test Link](https://dane-thomas.github.io/plugins/65804ff28f19ea7531883cf50c03fc4867bbb7bc/enhancedTable/samples/et-index.html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

fix(enhancedTable): fix menu close on keyboard up arrow press

---

enhancedTable/details-and-zoom-buttons.ts
enhancedTable/panel-manager.ts

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3348
Table not going transparent when using 
Table becomes transperent when zooming from details
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/59)

fix(enhancedTable): zoom from details makes table transparent

---

enhancedTable/config-manager.ts
enhancedTable/index.ts
enhancedTable/panel-manager.ts
lib/enhancedTable/config-manager.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3373
Layer wouldn't open for dynamic layers and for some layers whose proxys were slow to resolve. 
- Removes redundant recursion search for `legendBlock` and just uses `legendBlock` from `index.ts` (fixes sample 75 issue)
- Removes redundant check from `config-manager.ts`, same check is on line 36 of `index.ts`
you can test using the `table-open` branch I pushed to my viewer repo here: http://fgpv.cloudapp.net/demo/users/ShrutiVellanki/table-open/dev/samples/index-samples.html
- makes testing the samples easier
- make sure my deletions didn't break something that was working before this PR
n/a
-   [ ] Documentation is …

fix(enhancedTable): table opens for nested dynamic layers

---

enhancedTable/details-and-zoom-buttons.ts
enhancedTable/index.ts
lib/enhancedTable/config-manager.d.ts
lib/enhancedTable/config-manager.js
lib/enhancedTable/custom-floating-filters.d.ts
lib/enhancedTable/custom-floating-filters.js
lib/enhancedTable/details-and-zoom-buttons.d.ts
lib/enhancedTable/details-and-zoom-buttons.js
lib/enhancedTable/index.js
lib/enhancedTable/panel-manager.d.ts
lib/enhancedTable/panel-manager.js
lib/enhancedTable/panel-rows-manager.d.ts
lib/enhancedTable/panel-rows-manager.js

- Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3396
- updates build (so you only really have to look at `details-and-zoom-buttons.ts` and `index.ts`)
- Reason details and zoom was failing for `sample 2` was because `OBJECTID` was encoded as `ID` and the details/zoom buttons didn't know how to retrieve the oid and return proper details/properly zoom
- Determines proper `OBJECTID` field from `_layerProxy` and retrieves corresponding data that way (i.e. doesn't hard code `OBJECTID` anymore)
Test if sample 2 details/zoom work. Double check using other samples as well (on viewer PR).
-   [ …

fix(enhancedTable):  detect OID fields accurately

---

enhancedTable/index.ts
enhancedTable/panel-manager.ts
enhancedTable/panel-state-manager.ts

fgpv-vpgf/fgpv-vpgf#3337
Column visibility was being reset between loads.
Stores the column state from ag-grid and reloads it when needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/66)

fix(enhancedTable): keep column state on subsequent loads

---

bin/build/travis/ghpages-build.sh

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3411
RAMP source urls were not pointing to the correct location
Fixes the urls for gh-pages deploys
https://dane-thomas.github.io/plugins/ac23929eeefa802c5c63edec69d1d8cee843747c/enhancedTable/samples/et-index.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/74)

fix(build): fix RAMP source js and css urls

---

enhancedTable/index.ts
lib/enhancedTable/custom-header.js
lib/enhancedTable/index.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3439
Table doesn't close on layer remove
Adds an observer to close the table on layer removal
**NOTE: LIMITATIONS**
With these changes the table will close once the "undo remove" toast closes. 
Table will not close until all children are removed  for dynamic layers. 
https://dane-thomas.github.io/plugins/ff69e8c8d4fdb4633d7e3a4bb9e3d4d37b6a1bd4/enhancedTable/samples/et-index.html
---
This change is [<img …

fix(enhancedTable): close table on layer remove

---

enhancedTable/panel-manager.ts
lib/enhancedTable/panel-manager.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3450
When a filter is set on the table, NOT applied to map, and then cleared, the apply to map button is still enabled. 
This PR checks if the changed filter is different from the one applied to map, and only then enables the apply to map button.
^ test link takes a while to build with github pages
- set filter to table
- apply to map should be enabled,  DO NOT apply to map
- click clear filters
- apply to map should be disabled
- set filter to table
- apply to map should be enabled, apply to map
- click clear filters
- apply to map should be enabled
- click apply to map, apply to map should be disabled
- open layer with prexisting column filters
- do NOT apply to map
- clear filters
- apply to map should be disabled
-   [ ] Test specs are …

fix(enhancedTable): fix apply to map enable/disabling

---

enhancedTable/panel-manager.ts
lib/areasOfInterest/index.js
lib/enhancedTable/panel-manager.d.ts
lib/enhancedTable/panel-manager.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3463
`Apply To Map` and `Clear Filters` tool tips persistent after click in IE and Edge. 
- Tried for a long time to think of a more elegant way to do this, ended up forcing the remove of `md-show` class...seems to work.
- build update as usual `.js` files
Test in IE and Edge. Github pages takes a while to build test link
inline comments
---
This change is [<img src="https://reviewable.io/review_button.svg" …

fix(enhancedTable): persistent tooltips removed

---

areasOfInterest/index.ts
enhancedTable/index.ts
lib/areasOfInterest/index.js
lib/enhancedTable/index.d.ts
lib/enhancedTable/index.js
lib/enhancedTable/main.css
lib/enhancedTable/panel-manager.d.ts
lib/enhancedTable/panel-manager.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3447
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2547
3447 - datatable did not close on dynamic layer removal unless all children removed
2547 - no way to get extent through API or set with `fit` parameter
3447 - close datatable immediately on removal of any layer
2547 - modify the setter to a function with optional parameter and add get function
Testing Link: http://fgpv.cloudapp.net/demo/users/JahidAhmed/3447-legend-remove-observable/dev/samples/index-samples.html
-   [ ] PR has only one commit (squash …

3447 table closing correctly and 2547 api extent modifications

---

enhancedTable/details-and-zoom-buttons.ts
enhancedTable/panel-manager.ts
lib/enhancedTable/details-and-zoom-buttons.js
lib/enhancedTable/panel-manager.js

fgpv-vpgf/fgpv-vpgf#3481
Details zoom was broken, while fixing that some stuff was refactored causing some function calls in here to not do anything anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/95)

 refactor(enhancedTable): ramp zoom changes

---

enhancedTable/config-manager.ts
enhancedTable/panel-manager.ts
lib/enhancedTable/config-manager.js
lib/enhancedTable/panel-manager.js

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3506
Was a waterfall of errors with `sample 76` caused by reasons:
- when converting to uppercase, value was null
- when converting to uppercase, value was a string
Also Apply to Map had issues: 
- global query strings of less than three chars would activate `Apply to Map`
- `Apply to Map` was not activated for global query strings that make table empty
Also there was an issue with `layerEntries` erroring out. 
- added check for null values and converted each value to string
- added check for not activating `Apply to Map` for global query strings greater than 2
- added check for activating `Apply to Map` for global query strings that make table empty `1=2`
- fixed `layerEntry` errror out issue
`sample 76` …

fix(enhancedTable): fix global filter console errors

---

package-lock.json
package.json

Bumps plugins up to `v3.0.0`: 
Tag: https://github.com/fgpv-vpgf/plugins/tree/v3.0.0
On npm: https://registry.npmjs.org/@fgpv/rv-plugins/ `v3.0.0` should show up there after a little bit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/101)

fix(plugins): version bump

---

enhancedTable/panel-manager.ts
lib/enhancedTable/panel-manager.js

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3494
All of the following test cases used to fail. 
- **Test 1**: does closing and opening retain the table filter? 
- **Test 2**: 
- Open table
- Apply to Map
- Clear Filter
- Apply to Map should be active
- **Test 3**: 
- Open Table
- Apply to Map, now Apply to Map should be disabled
- Close and reopen table
- Apply to map should still be disabled
- Clear filters
- Apply to Map should be enabled
- **Test 4**: 
- Open table
- Toggle Table visibility off
- Close and reopen the table. Clear filters and apply to map buttons should still be active
Now the above test cases should pass.
-   [x] Documentation is up-to-date …

fix(enhancedTable): fix table filter and apply to map

---

enhancedTable/panel-manager.ts
lib/enhancedTable/panel-manager.js

Issue: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3543
Connected to: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3546
The global filter results displayed on the table were different from the results displayed on the map. This is because the table displays points that have a column that contains the global query, while the map was only displaying the points where ALL of the columns contained the global query.
This problem was solved by changing the `AND` to an `OR` in the query generator. This PR also fixes a problem where the query string would contain duplicate queries.
-   [ ] …

fix(enhancedTable): fix global search incorrectly applying to map

---

enhancedTable/index.ts
lib/enhancedTable/config-manager.js
lib/enhancedTable/index.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3509
Table did not build successfully because it did not recognize it was already open
Since the table is still open after reload, it now closes it as expected
-   ~~[ ] Test specs are up-to-date & cover all changes/additions made by this PR.~~
-   ~~[ ] `npm run test` passes locally.~~
-   ~~[ ] Documentation is up-to-date - any changes or additions have been noted~~
-   ~~[ ] `changelog.md` has been updated~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/104)

fix(table): compare apiLayer instead of legendBlock on reload

---

enhancedTable/index.ts
lib/enhancedTable/index.js

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3589
Table did not respect column order as defined in config
Table respects column order if defined, and sets default column order if not defined
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/109)

fix(enhancedTable): column order respects config

---

enhancedTable/details-and-zoom-buttons.ts
lib/enhancedTable/details-and-zoom-buttons.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3175
In order to display the custom field alias on the details panel properly, slight changes needed to be made to the table.
The table, when building the details panel, can properly access the required attributes in order to show the correct alias.
-   ~~[ ] Test specs are up-to-date & cover all changes/additions made by this PR.~~
-   ~~[ ] `npm run test` passes locally.~~
-   ~~[ ] Documentation is up-to-date - any changes or additions have been noted~~
-   ~~[ ] `changelog.md` has been updated~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

feat(ui): add support for field alias definitions

---

enhancedTable/panel-manager.ts
lib/enhancedTable/panel-manager.d.ts
lib/enhancedTable/panel-manager.js

Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3620
Needed to update `list` and `item` classes to less common names
Updated all instances of class `list` to `rv-focus-list` and all instances of `item` to `rv-focus-item`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/113)

fix(enhancedTable): update list and item classes

---

enhancedTable/templates.ts
lib/enhancedTable/templates.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3632
When a value is entered into only one of the `max` and `min` column filters, the value of the empty field when the table is closed and reopened is `NaN`.
The empty value no longer reads `NaN`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/116)

fix(enhancedTable): number filter displays empty value properly

---

enhancedTable/index.ts
lib/enhancedTable/index.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3634
When trying to open the datagrid of some WFS layers, the table would never load. This was due to the fact that WFS layers can have attributes of type `object`. 
This PR fixes the problem by temporarily replacing objects with `Complex Value` so the table opens. This PR is mainly just so the table will open again. A more permanent solution to this problem should be found in the future.
---
This change is [<img …

fix(enhancedTable): fix broken table when row contains complex values

---

coordInfo/index.ts

#90 
This if statement was no longer needed
Removed check for HTTP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/123)

fix(coordInfo): remove check for http

---

enhancedTable/custom-floating-filters.ts
enhancedTable/panel-manager.ts
enhancedTable/panel-state-manager.ts
lib/enhancedTable/custom-floating-filters.js
lib/enhancedTable/panel-manager.js
lib/enhancedTable/panel-state-manager.js

fgpv-vpgf/fgpv-vpgf#3647
Filtering using special characters (such as `?^.|`) does not filter column data appropriately. 
Escape all special characters before setting/applying column filters. The `%` character is handled as a special case in the where clause using: `... LIKE '%'ௌ%%' ESCAPE ''ௌ'` to meet ESRI formatting standards. This case needs handling in the geoApi SQL parser. The only special char that will not work is `*`, since it is used for properties like `lazyFilter`. 
-   [x] Commit message is …

fix(enhancedTable): fix grid special chars filtering

---

enhancedTable/config-manager.ts
enhancedTable/index.ts
enhancedTable/panel-manager.ts
enhancedTable/panel-state-manager.ts
lib/enhancedTable/config-manager.js
lib/enhancedTable/index.js
lib/enhancedTable/panel-manager.js
lib/enhancedTable/panel-state-manager.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3665
Sister PR: on the way
Adds the ability to have `filter by extent` and `show filters` disabled by default.
Implements above
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/122)

feat(enhancedTable): add schema options to disable show filters by default

---

enhancedTable/main.scss
lib/enhancedTable/main.css

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3681
Cell contents could not be selected.
Cell contents can now be selected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/128)

fix(enhancedTable): allow cell contents to be selected

---

bin/build/travis/dist-build.sh

The **number** of builds that are failing haaaaa 👴 
Upon a second build on a branch, the command to move new docs into doc folder would fail because the docs of the previous build were still lurking there.
Command added to clean out any old docs.
Command provided courtesy of Muffin Engineer Petrov.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/131) …

clear out any old doc pages

---

enhancedTable/index.ts
lib/enhancedTable/index.js

fgpv-vpgf/fgpv-vpgf#3652
Any long/lat with a zero value will have its cell value show up as blank 
Check if `cell.value` is a number since `cell.value` evaluates to false when it is zero
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/130)

fix(enhancedTable): fix coord zero values showing up as blanks in grid

---

enhancedTable/custom-floating-filters.ts
enhancedTable/panel-manager.ts
lib/enhancedTable/custom-floating-filters.js
lib/enhancedTable/panel-manager.js

Closes fgpv-vpgf/fgpv-vpgf#3694 and fgpv-vpgf/fgpv-vpgf#3689
Could not correctly apply filters to map for lat/long columns because it was treated as string values. Other problems included not being able to filter number columns such as OBJECTID with negative values and using any string character following a number would delete the entire filter value. 
GeoApi now changes CSV files to `esriFieldTypeDouble` so lat/long columns can be filtered in the same way as OBJECTID and other number columns. Added more checks for `-` input to represent searching for negative value ranges and reverted filter input back to the previous filter value that was still a number value. 
-   [ ] …

fix(enhancedTable): fix lat/long map filtering

---

enhancedTable/index.ts
lib/enhancedTable/index.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3722
Datatables do not open for some layers in IE because IE does not support `Number.isInteger()`.
Replaced with `!isNaN()` to keep the same functionality. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/139)

fix(enhancedTable): fix table not opening in IE

---

enhancedTable/index.ts
enhancedTable/panel-manager.ts
lib/enhancedTable/index.js
lib/enhancedTable/panel-manager.js

Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3674
Closing and reopening a table after turning `Show Filters` off causes table to be unfiltered until `Show Filters` is turned back on.
Reset the `tableOptions.floatingFilter` value and toggle it once when grid is ready after reopen to trigger `onFloatingFilterChanged` in `custom-floating-filters` which will initialize the filters normally.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

fix(enhancedTable): fix column filters on table reopen with Show Filters off 

---

enhancedTable/main.scss
lib/enhancedTable/main.css

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3737
When there are no rows to display in the table, the horizontal scroll bar will disappear.
Adds a minimum height to the table body. The height was previously being set to 1px, which is removing the scroll bar for some reason. 2px works just fine 😄 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/144)

fix(enhancedTable): fix horizontal scroll not appearing in Chrome

---

enhancedTable/custom-floating-filters.ts
lib/enhancedTable/custom-floating-filters.js

https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3736
Filtering with special characters did not work for layers with `lazyFilter` enabled. 
Write a separate regex filtering `textCustomComparator` for tables with `lazyFilter` enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/145)

fix(enhancedTable): fix filters for tables with lazyFilters enabled
