fgpv-vpgf/plugins

areaOfInterest/areas-of-interest.ts, areaOfInterest/html-assets.ts, areaOfInterest/package-lock.json, areaOfInterest/package.json, webpack.config.js
Helps close https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2787, supports https://github.com/fgpv-vpgf/fgpv-vpgf/pull/2880
=> add area of interest extension

enhancedTable/index.ts
Changes support this PR on viewer repo: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3092
Resolves points 1, 2, 5 in this issue: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3079
`enhancedTable` now has: 
- hovertip for close button
- properly formatted titles
- svgs that show up the first time table is opened
- properly rendered SVGs 
- tooltips that show up for titles that are cut off
=> fix(enhancedTable): svgs, column titles and hovers render correctly

enhancedTable/package-lock.json, enhancedTable/panel-manager.ts, enhancedTable/templates.ts, package-lock.json
Supports: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3098
Adds:
- clear filters button
- dropdown menu to select columns to display
Implements part of https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3088
=> feat(enhancedTable): add clear filters and column visibility dropdown

enhancedTable/index.ts, enhancedTable/main.scss, enhancedTable/package-lock.json, enhancedTable/panel-manager.ts, enhancedTable/templates.ts, libs/ramp/rv-styles.css
Supports: fgpv-vpgf/fgpv-vpgf#3103
Adds:
- toggle column filter visibility
Fixes: 
- symbol and interactive column visibilities were togglable
- table would only open on second click
Implements part of fgpv-vpgf/fgpv-vpgf#3077
=> Fix table opening and add ability to hide column filters

libs/ramp/rv-styles.css
Forgot to update build for this PR: https://github.com/fgpv-vpgf/plugins/pull/10
everything should be good when you do an `npm run serve` on the extensions repo
=> Build updated for filter status, padding, sorting indicator

enhancedTable/index.ts
Change code to match api compile changes in https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3166
=> fix(filters): update api compile usage in table

bin/test/ramp.page.js, bin/test/ramp/rv-styles.css, enhancedTable/details-and-zoom-buttons.ts, enhancedTable/index.ts, enhancedTable/panel-manager.ts, enhancedTable/panel-rows-manager.ts, enhancedTable/panel-status-manager.ts, enhancedTable/samples/ramp-config.json, enhancedTable/templates.ts, enhancedTable/tests/et.page.js, enhancedTable/tests/symbol-visibility.spec.js, enhancedTable/tests/test-details-zoom.spec.js
- Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3158
- Also refactors existing code which I explain [here](https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3187#issuecomment-447493142) 
`enhancedTable` was missing details and zoom buttons
This PR adds details and zoom buttons for each row of an `enhancedTable`
-   [x] `changelog.md` has been updated
=> Add Details and Zoom Buttons, Refactor Status and Row Visibility Code

enhancedTable/custom-floating-filters.ts, enhancedTable/custom-header.ts, enhancedTable/grid-accessibility.ts, enhancedTable/index.ts, enhancedTable/main.scss, enhancedTable/panel-manager.ts, enhancedTable/templates.ts, enhancedTable/tests/et.page.js, enhancedTable/tests/filter-test.spec.js, enhancedTable/tests/header-test.spec.js, enhancedTable/tests/symbol-visibility.spec.js, enhancedTable/tests/test-details-zoom.spec.js, enhancedTable/tests/test.spec.js
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3157
Column headers not accessible 
Sort now done through accessible button containing the column name.
Reordering can now be done through buttons in right side of the column header. 
**NOTE: Two tests are broken for checking symbology visibility toggles and we're fairly convinced it's not because of my changes. @ShrutiVellanki is currently looking into them!**
=> feat(enhancedTable): add column header accessibility

enhancedTable/config-manager.ts, enhancedTable/custom-floating-filters.ts, enhancedTable/index.ts, enhancedTable/panel-manager.ts, enhancedTable/samples/ramp-config.json, enhancedTable/templates.ts, enhancedTable/tests/symbol-visibility.spec.js
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3185
`enhancedTable` needs to be synced to config file 
In depth coverage list on sister PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3203#issue-240574852
UI Tests not applicable for this PR
-   ~[ ] Test specs are up-to-date & cover all changes/additions made by this PR.~
-   ~[ ] `npm run test` passes locally.~
=> fix(enhancedTable): sync table and column config, refactor filter code

enhancedTable/custom-header.ts, enhancedTable/index.ts, enhancedTable/panel-manager.ts
n/a
Bugs found relating to column visibility
- Columns break when toggling visibility
- Headers disappear after hiding then showing a column
- If no columns are defined in the config all columns have undefined visibility
- Add missing function `destroy` for column header
- Add check if there are any columns defined in the config before assigning visibility
https://dane-thomas.github.io/plugins/708adbc42769db88a3c95022536ebbca32f200c2/enhancedTable/samples/et-index.html
-   [x] Commit message is …
=> fix(enhancedTable): fix column visibility bugs

bin/test/ramp/rv-styles.css, enhancedTable/custom-header.ts, enhancedTable/details-and-zoom-buttons.ts, enhancedTable/index.ts, enhancedTable/main.scss, enhancedTable/panel-manager.ts, enhancedTable/panel-status-manager.ts, enhancedTable/templates.ts
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3105
Enhanced table is not mobile compatible
Draws table over legend when opened and adds "expanding section" for the panel controls (search, clear filters, etc.)
https://dane-thomas.github.io/plugins/ca6232c7698f2276f47432246adcd85eb8fc6b3b/enhancedTable/samples/et-index.html
=> feat(enhancedTable): add mobile compatibility

enhancedTable/config-manager.ts, enhancedTable/custom-floating-filters.ts, enhancedTable/index.ts, enhancedTable/panel-manager.ts, enhancedTable/panel-status-manager.ts, enhancedTable/print-table.html, enhancedTable/samples/ramp-config.json, enhancedTable/templates.ts
Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3240, https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3238
Sister PRs on Viewer: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3253, https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3245
Column filters would disappear when column visibilities were toggled, filter flags were out of sync with table. Print was rarely used, didn't render all columns. 
- Table filters are synced to table filter flag
- Column filters are preserved when column is toggled on/off
- This situation is not happening in IE anymore
- When static filters are present, clear filters button is disabled
- Global search is fixed
- Table symbologies are center aligned (vertically and horizontally)
- Printing table results in a nicely formatted HTML table. Print option is disabled …
=> fix(enhancedTable): column state and filter flag sync, printing enabled from config

enhancedTable/panel-manager.ts, enhancedTable/panel-rows-manager.ts
Updating function names to match enhanced geoApi filters
=> refactor(enhancedTable): update filter function names

enhancedTable/config-manager.ts, enhancedTable/panel-manager.ts, enhancedTable/panel-rows-manager.ts, enhancedTable/panel-status-manager.ts, enhancedTable/templates.ts, package-lock.json
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3156
Finishing integration using filter observer and apply to map condition
Integrate filter changes using the new filter change observable. 
Add condition so apply to map button is only active after the filters have been changed. 
https://dane-thomas.github.io/plugins/a6052e1658c82044607942c94ee19af2be41621d/enhancedTable/samples/et-index.html
=> refactor(enhancedTable): use new filter change observable

bin/build/webpack.config.js, bin/test/ramp/rv-styles.css, coordInfo/docs/README.md, coordInfo/docs/index.html, coordInfo/html-assets.ts, coordInfo/index.ts, coordInfo/samples/coordinfo-index.html, coordInfo/samples/ramp-config.json, enhancedTable/index.ts, tsconfig.json
fgpv-vpgf/fgpv-vpgf/#3242
Moving coordInfo plugin to v3
https://spencerwahl.github.io/plugins/bb5cbda592774ae644e87765a502fc0b1e892e76/coordInfo/samples/coordinfo-index.html
-   [x] `changelog.md` has been updated
=> feat(coordInfo): add coordInfo plugin

enhancedTable/custom-floating-filters.ts, enhancedTable/index.ts, enhancedTable/panel-manager.ts
Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3263
- faulty number filtering with text columns
- selector filters not clearing properly
- default but hidden column filters were not properly applied to table
- `simpleTable` render under `enhancedTable`
- post integration work:  cleanup of legend.block/proxywrapper .definitionQuery . Ensure app is using modern channels for adjusting filters.
This PR addresses first four bullet points. Sister PR addresses the last one
-   ~[ ] Test specs are up-to-date & cover all changes/additions made by this PR.~
-   ~[ ] `npm run test` passes locally.~
-   ~[ ] `changelog.md` has been updated~
-   [x] Commit message is …
=> fix(enhancedTable): fix minor table bugs, integration refactor

bin/test/ramp/rv-styles.css, enhancedTable/index.ts
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3281
Table doesn't open when using legend item menu option
Opens table when using the legend item menu option
=> fix(enhancedTable): open table with legend entry menu option

enhancedTable/main.scss, enhancedTable/panel-manager.ts, enhancedTable/templates.ts
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3305
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3309
Global search not tied to clear filters button
Global search field too small in IE
Also a small template refactor to fix table menu in mobile 
Global search is now cleared by clear filters button
Global search field now proper width
https://dane-thomas.github.io/plugins/659d8a61e2fcbca9c1b703d4f331185fda7e58a1/enhancedTable/samples/et-index.html
=> fix(enhancedTable): global search not wide IE

compileSass.sh, enhancedTable/index.ts, enhancedTable/main.scss, enhancedTable/panel-manager.ts, index.ts, package-lock.json, package.json
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3311
Finishes up https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3299
Column visibility toggles were in a confusing order
Enable enhanced table by default and import as an npm package
Put the column visibility toggles in alphabetical order
=> fix(enhancedTable): column selector in alpha order

enhancedTable/panel-manager.ts
adds above fix to `v3` as requested by @james-rae 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/58)
=> fix(enhancedTable): prevent huge lazy filter sql clauses

enhancedTable/panel-manager.ts, lib/enhancedTable/panel-manager.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3347
Console errors from the table in v3
Fixes errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/60)
=> fix(enhancedTable): console errors

bin/test/ramp/rv-styles.css, enhancedTable/index.ts, enhancedTable/panel-loader.ts, enhancedTable/panel-manager.ts, lib/enhancedTable/index.js, lib/enhancedTable/panel-loader.js, lib/enhancedTable/panel-manager.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3368
Enhanced needs to be migrated to new panel api changes
Migrates the panels
https://dane-thomas.github.io/plugins/13f0a5c6641836e825e925c71d210f30f6d2eeb2/enhancedTable/samples/et-index.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/68)
=> fix(enhancedTable): regressions after panel api refactor

bin/test/ramp/rv-styles.css, enhancedTable/index.ts, lib/enhancedTable/config-manager.d.ts, lib/enhancedTable/config-manager.js, lib/enhancedTable/custom-floating-filters.d.ts, lib/enhancedTable/custom-floating-filters.js, lib/enhancedTable/index.js, lib/enhancedTable/panel-manager.d.ts, lib/enhancedTable/panel-manager.js, lib/enhancedTable/panel-rows-manager.d.ts, lib/enhancedTable/panel-rows-manager.js
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3221
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3288 as well
Ensure table opens after the panel api changes and panels react to each other properly 
Uses the updated observable 
https://dane-thomas.github.io/plugins/0a81789b7358e28f4a763247e96bbb555073d2ce/enhancedTable/samples/et-index.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> fix(enhancedTable): update table open observable

lib/enhancedTable/index.js, lib/enhancedTable/panel-manager.d.ts, lib/enhancedTable/panel-manager.js, lib/enhancedTable/panel-state-manager.d.ts, lib/enhancedTable/panel-state-manager.js
I forgot to update lib in #66 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/71)
=> chore(enhancedTable): update lib

enhancedTable/panel-manager.ts, lib/enhancedTable/panel-manager.js, package-lock.json
Fixes issues on the RAMP prod build, the dependencies for `ToastCtrl` were being minified and not recognized by angular.
Uses explicit dependency listing when registering the controller which makes sure Angular knows what its looking at.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/76)
=> fix(enhancedTable): fix toastctrl dependencies

enhancedTable/custom-header.ts, enhancedTable/index.ts, enhancedTable/main.scss, lib/enhancedTable/custom-header.d.ts, lib/enhancedTable/custom-header.js, lib/enhancedTable/index.js, lib/enhancedTable/main.css
Closes https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3413
Reorder buttons were not being enabled/disabled when moved from/to left or right most position.
Sort arrow was not being updated on sort button press
calls angular apply to apply the changes immediately
https://dane-thomas.github.io/plugins/267796039147fd97695de7f283c84d9bb95588ab/enhancedTable/samples/et-index.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> fix(enhancedTable): column reorder buttons enabling

enhancedTable/index.ts, enhancedTable/main.scss, enhancedTable/panel-manager.ts, lib/enhancedTable/custom-header.js, lib/enhancedTable/index.js, lib/enhancedTable/main.css, lib/enhancedTable/panel-manager.d.ts, lib/enhancedTable/panel-manager.js
Supports: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3421
Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3294
Make keyboard navigation on `enhancedTable` more accessible
Adds the appropriate classes and listeners to work properly with `InternalsFocusManager` on sister PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/78)
=> fix(enhancedTable): add list and item attributes

areasOfInterest/index.ts, areasOfInterest/samples/aoi-config-nopics.json, areasOfInterest/samples/aoi-config-pics.json, areasOfInterest/samples/nopics.html, areasOfInterest/samples/pics.html, package-lock.json, package.json
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3440
Extra scrollbar, error thrown when exiting fullscreen, weird layer setup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/82)
=> fix(areasOfInterest): styles, fullscreen, layers

bin/test/ramp/rv-styles.css, coordInfo/index.ts, lib/coordInfo/index.js
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3446
Coordinate Info did not use to work on projection change.
Added a tag to HTML map element to detect if coordInfo should be active on creation.
inline comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/84)
=> fix(coordInfo): works on projection change

enhancedTable/index.ts, enhancedTable/main.scss, enhancedTable/panel-manager.ts, package-lock.json, package.json
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3469
clicking on layer wouldn't toggle the panel closed
panel now closes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/89)
=> fix(enhancedTable): header css, layers toggling table

bin/test/ramp/rv-styles.css, enhancedTable/config-manager.ts, enhancedTable/index.ts, enhancedTable/panel-manager.ts, enhancedTable/samples/et-cam.html, enhancedTable/samples/ramp-config-cam.json, lib/enhancedTable/config-manager.js, lib/enhancedTable/index.js, lib/enhancedTable/panel-manager.d.ts, lib/enhancedTable/panel-manager.js
Please enter the commit message for your changes. Lines starting
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3477
- on tables linked to  `layerEntries`, columns that should be hidden (according to config) are not hidden
- on tables NOT linked to `layerEntries`  columns that should be hidden (according to config) ARE hidden (with exception of columns that have filters)
- on tables linked to  `layerEntries` with column filters, column filters don't show
- when adding a column filter to tables linked to `layerEntries` the filter doesn't show up
- Fixes the above issues
- Updates plugins build
- first layer: layerEntry with hidden column (OBJECTID) with default filter
- second layer: regular layer with hidden column
- third layer: regular layer with hidden column and default filter
Test …
=> fix(enhancedTable): columns hidden according to config

enhancedTable/panel-manager.ts, lib/enhancedTable/panel-manager.js, package-lock.json, package.json
Closes: https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3475
Sister PR: https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3505
Headers were disappearing in IE when you scrolled.
Fixes ^ plus other general internet explorer laginess
Test on `Liquids Pipline` or `Natural Gas` or any other table with offscreen columns
**Please Check the following in All Three Browsers because these were recurring issues when I was trying to solve this:**
- when you forward and backtab and use arrow keys to move through table cells, headers don't disappear
- when you tab through the header buttons and press enter the columns switch
- when you press backtab when in a cell should focus on filter row
- if you enter into grid cells you can navigate properly using arrow keys
- you can forward and backtab properly …
=> fix(enhancedTable): fix headers disappearing in IE

enhancedTable/config-manager.ts, lib/enhancedTable/config-manager.js, package-lock.json, package.json
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3477
Reverted to not hiding not visible columns propperly. 
This PR ensures columns hidden properly according to config specifications. 
Test other dynamic layers to make sure they don't break.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/100)
=> fix(enhancedTable): hide not visible columns

enhancedTable/config-manager.ts, lib/enhancedTable/config-manager.js, package-lock.json, package.json
Version bump/ patch to solve for nested dynamic layers not opening table for `v3` release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/102)
=> fix(plugins): version bump to 3.0.1

enhancedTable/index.ts, lib/enhancedTable/index.js, package-lock.json
https://github.com/fgpv-vpgf/fgpv-vpgf/issues/3588
Viewer PR https://github.com/fgpv-vpgf/fgpv-vpgf/pull/3592
Table was rendering html as plain text.
Renders html as is and wraps plain text in a `<p>` tag. 
http://fgpv.cloudapp.net/demo/users/dane-thomas/html-column/dev/samples/index-samples.html?sample=88
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plug …
=> fix(enhancedTable): html rendering as text in columns

package-lock.json, package.json
Updating the version for testing glory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/141)
=> version bump 3.2.0-1

package-lock.json, package.json
Updating version to make fancy builds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/plugins/146)
=> Version bump 3.2.0-3
